name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  TAG: latest

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SERVICE_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SERVICE_SECRET_KEY }}
          aws-region: eu-west-1
      - name: ECR Login
        id: ecr-login
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 436376758376.dkr.ecr.eu-west-1.amazonaws.com
      - name: Move Dir
        id: move-dir
        run: |
          cd train
 
      - name: Build the Docker image
        id: build
        run: docker build . --file Dockerfile --tag 436376758376.dkr.ecr.eu-west-1.amazonaws.com/sagemaker/example-train-pipeline:$TAG
  

      - name: Push the Docker image
        id: push-image
        run: docker push 436376758376.dkr.ecr.eu-west-1.amazonaws.com/sagemaker/example-train-pipeline:$TAG
